# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:

  pull_request_target:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  prtargetci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!


